language: java

jdk:
  - oraclejdk8

# git strips the wrapper jar file so we have to force its download during the build

before_install:
  git update-index --chmod=+x mvnw

install:
# - mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- ./mvnw test
- ./mvnw javadoc:aggregate
